aws_regions= [
    "US East (Ohio)",
    "US East (N. Virginia)",
    "US West (N. California)",
    "US West (Oregon)",
    "Africa (Cape Town)",
    "Asia Pacific (Hong Kong)",
    "Asia Pacific (Hyderabad)",
    "Asia Pacific (Jakarta)",
    "Asia Pacific (Melbourne)",
    "Asia Pacific (Mumbai)",
    "Asia Pacific (Osaka)",
    "Asia Pacific (Seoul)",
    "Asia Pacific (Singapore)",
    "Asia Pacific (Sydney)",
    "Asia Pacific (Tokyo)",
    "Canada (Central)",
    "Canada West (Calgary)",
    "Europe (Frankfurt)",
    "Europe (Ireland)",
    "Europe (London)",
    "Europe (Milan)",
    "Europe (Paris)",
    "Europe (Spain)",
    "Europe (Stockholm)",
    "Europe (Zurich)",
    "Israel (Tel Aviv)",
    "Middle East (Bahrain)",
    "Middle East (UAE)",
    "South America (São Paulo)",
    "AWS GovCloud (US-East)",
    "AWS GovCloud (US-West)"
]
azure_regions = [
    "East US", "East US 2", "South Central US", "West US 2", "West US 3",
    "Australia East", "Southeast Asia", "North Europe", "Sweden Central",
    "UK South", "West Europe", "Central US", "South Africa North",
    "Central India", "East Asia", "Japan East", "Korea Central",
    "Canada Central", "France Central", "Germany West Central",
    "Italy North", "Norway East", "Poland Central", "Switzerland North",
    "UAE North", "Brazil South", "Central US EUAP", "Israel Central",
    "Qatar Central", "Central US (Stage)", "East US (Stage)",
    "East US 2 (Stage)", "North Central US (Stage)", "South Central US (Stage)"
]
gcp_regions = [
    "Oregon (us-west1)", "Los Angeles (us-west2)", "Salt Lake City (us-west3)",
    "Las Vegas (us-west4)", "Iowa (us-central1)", "South Carolina (us-east1)",
    "N. Virginia (us-east4)", "Columbus (us-east5)", "Dallas (us-south1)",
    "Montréal (northamerica-northeast1)", "Toronto (northamerica-northeast2)",
    "Santiago (southamerica-west1)", "São Paulo (southamerica-east1)",
    "London (europe-west2)", "Belgium (europe-west1)", "Netherlands (europe-west4)",
    "Zurich (europe-west6)", "Frankfurt (europe-west3)", "Finland (europe-north1)",
    "Warsaw (europe-central2)", "Milan (europe-west8)", "Madrid (europe-southwest1)",
    "Paris (europe-west9)", "Turin (europe-west12)", "Berlin (europe-west10)",
    "Mumbai (asia-south1)", "Delhi (asia-south2)", "Singapore (asia-southeast1)",
    "Jakarta (asia-southeast2)", "Hong Kong (asia-east2)", "Taiwan (asia-east1)",
    "Tokyo (asia-northeast1)", "Osaka (asia-northeast2)", "Sydney (australia-southeast1)",
    "Melbourne (australia-southeast2)"
]